//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public string SubId { get; set; }
        public string UserId { get; set; }
        public int NumAnswer { get; set; }
        public int NumAnswerTrue { get; set; }
        public int TimeUse { get; set; }

        [JsonIgnore]
        public AspNetUser AspNetUser { get; set; }
        [JsonIgnore]
        public Subject Subject { get; set; }
    }
}
