//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public string Version { get; set; }
        public string Coder { get; set; }
        public string Designer { get; set; }
        public string Analysis { get; set; }
        public string Tester { get; set; }
        public string DBBuilding { get; set; }
    }
}
