//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventStyle()
        {
            this.EventStatus = new HashSet<EventStatus>();
        }
    
        public string EventName { get; set; }
        public string FirstPath { get; set; }
        public string SecondPath { get; set; }
        public string ThirdPath { get; set; }
        public string FourthPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventStatus> EventStatus { get; set; }
    }
}
