//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
    }
}
