//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public string SubId { get; set; }
        public int UserId { get; set; }
        public int NumAnswer { get; set; }
        public int NumAnswerTrue { get; set; }
        public int TimeUse { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
