//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string SubId { get; set; }
        public string Content { get; set; }
        public string Opt1 { get; set; }
        public string Opt2 { get; set; }
        public string Opt3 { get; set; }
        public string Opt4 { get; set; }
        public string Answer { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string UserAdd { get; set; }
        public string Note { get; set; }

        public string Traloi { get; set; }
        public bool IsCorrect
        {
            get {
                if (this.Traloi == null) return false;
                else return this.Traloi.Equals(this.Answer);
                }
        }
        public virtual Subject Subject { get; set; }
    }
}
